bolletjes: 0.95
hoorentjes: 1.25
bakjes: 0.8
toppings:
  slagroom: 0.55
  bottetjes: 0.35
  caramel:
    bakje: 0.8
    hoorentje: 0.6
toppingList: ["chocolate","Water", "Milk"]
liter: 8.99
btw: 6
smaken: ["chocolate","strawberry","berry","coffee","vanilla","cheese","chicken"]
